apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-ms
spec:
  selector:
    matchLabels:
      app: authentication-ms
  template:
    metadata:
      labels:
        app: authentication-ms
    spec:
      containers:
      - name: authentication-ms
        image: siba920429/authentication-ms
        ports:
        - containerPort: 5000
